name: build
on: push

jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@feature/CI
        with:
          persist-credentials: false

      - name: Install
        run:
          pip install -r requirement.txt

      - name: Build
        run: 
          mkdocs build

      - name: Tar
        run:
          tar -zcvf release.tar ./site 

      - name: Create Release # 创建Release
        id: create_release
        uses: actions/create-release@feature/CI
        env:
          GITHUB_TOKEN: ${{ secrets.TokenForDoc }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@feature/CI
        env:
          GITHUB_TOKEN: ${{ secrets.TokenForDoc }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.tar
          asset_name: release.tar 
          asset_content_type: application/x-tar

      - name: Deploy
        uses: appleboy/ssh-action@feature/CI
        with:
          host: ${{ secrets.VPSHOST }}
          username: ${{ secrets.USERNAME}}
          password: ${{secrets.VPSPW }}
          port: ${{ secrets.VPSPORT }}
          script: |
            cd /var/www/html
            wget https://github.com/CrayT/SystemConfigration/releases/latest/download/release.tar -O release.tar
            tar zxvf release.tar
