name: build
on: push

jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run:
          pip install -r requirement.txt

      - name: Build
        run: 
          mkdocs build

      - name: Deploy to Server 
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:
          ssh_private_key: ${{ secrets.VPSSSHKEY }}
          local_path: ./site/*
          server: ${{ secrets.VPSHOST }}
          username: ${{ secrets.USERNAME }}
          remote_path: ${{ secrets.VPSPATH }}

      - name: Reload
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPSHOST }}
          username: ${{ secrets.USERNAME}}
          password: ${{secrets.VPSPW }}
          port: ${{ secrets.VPSPORT }}
          script: |
            nginx -s reload