name: build
on: 
  push:
    branches:
      - master

jobs:
  buildJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run:
          pip install mkdocs 
          pip install mkdocs-material
  deployJob:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run:
          mkdocs gh-deploy --clean
